### PR TITLE
export as type when enumStyle is type

### PR DESCRIPTION
**Pull request by sleewoo**
fix for #361

### CODE REVIEW

**Comment by kristiandupont** [comment]
So obviously there are no tests for the index generator which is a problem that I don't expect you to fix here. Did you try it out? Because if so I will trust that it works and deploy.

**Comment by sleewoo** [comment]
yep, tested on live project, with both styles.
when enumStyle is type it is prepending type.
otherwise it just imports without prefix, as it should for enum.

**Comment by sleewoo** [comment]
Screenshot_20230125_143413

**Comment by sleewoo** [comment]
the `Enum` suffix added per my project, via `getMetadata`

**Comment by kristiandupont** [comment]
Awesome, thank you!

**Pull request merged**
