### PR TITLE
Fix escaping table names and fields

### LINKED ISSUE #505: bug: Tables with special characters or spaces in their names don't generate valid TypeScript
Example:

```
CREATE TABLE "[example] this is a table! yes, even with symbols: ""'!." (
  "id" text PRIMARY KEY,
  "Field names can have special characters too! (like this: []."")" text,
  "we_should_ensure_normal_naming_works" integer
);
```

Generates:

<details>
<summary>
kanel
</summary>

```ts
// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.[example] this is a table! yes, even with symbols: "'!. */
export type [example] this is a table! yes, even with symbols: "'!.Id = string & { __brand: '[example] this is a table! yes, even with symbols: "'!.Id' };

/** Represents the table public.[example] this is a table! yes, even with symbols: "'!. */
export default interface [example] this is a table! yes, even with symbols: "'!. {
  id: [example] this is a table! yes, even with symbols: "'!.Id;

  'Field names can have special characters too! (like this: [].")': string | null;

  we_should_ensure_normal_naming_works: number | null;
}

/** Represents the initializer for the table public.[example] this is a table! yes, even with symbols: "'!. */
export interface [example] this is a table! yes, even with symbols: "'!.Initializer {
  id: [example] this is a table! yes, even with symbols: "'!.Id;

  'Field names can have special characters too! (like this: [].")'?: string | null;

  we_should_ensure_normal_naming_works?: number | null;
}

/** Represents the mutator for the table public.[example] this is a table! yes, even with symbols: "'!. */
export interface [example] this is a table! yes, even with symbols: "'!.Mutator {
  id?: [example] this is a table! yes, even with symbols: "'!.Id;

  'Field names can have special characters too! (like this: [].")'?: string | null;

  we_should_ensure_normal_naming_works?: number | null;
}
```

</details> 

<details>
<summary>
kanel-kysely
</summary>

```ts
// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as [example] this is a table! yes, even with symbols: "'!.Table } from './[example] this is a table! yes, even with symbols: "'!.';

export default interface PublicSchema {
  '[example] this is a table! yes, even with symbols: "'!.': [example] this is a table! yes, even with symbols: "'!.Table;
}
```

```ts
// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.[example] this is a table! yes, even with symbols: "'!. */
export type [example] this is a table! yes, even with symbols: "'!.Id = string & { __brand: '[example] this is a table! yes, even with symbols: "'!.Id' };

/** Represents the table public.[example] this is a table! yes, even with symbols: "'!. */
export default interface [example] this is a table! yes, even with symbols: "'!.Table {
  id: ColumnType<[example] this is a table! yes, even with symbols: "'!.Id, [example] this is a table! yes, even with symbols: "'!.Id, [example] this is a table! yes, even with symbols: "'!.Id>;

  'Field names can have special characters too! (like this: [].")': ColumnType<string | null, string | null, string | null>;

  we_should_ensure_normal_naming_works: ColumnType<number | null, number | null, number | null>;
}

export type [example] this is a table! yes, even with symbols: "'!. = Selectable<[example] this is a table! yes, even with symbols: "'!.Table>;

export type New[example] this is a table! yes, even with symbols: "'!. = Insertable<[example] this is a table! yes, even with symbols: "'!.Table>;

export type [example] this is a table! yes, even with symbols: "'!.Update = Updateable<[example] this is a table! yes, even with symbols: "'!.Table>;
```

</details>

I appreciate it's fairly cursed in Postgres to have tables with special characters or spaces in their names, but a project I'm working on at the moment requires it.

### PR DESCRIPTION
**Pull request by domdomegg**
Fixes #505

### CODE REVIEW

**Comment by domdomegg** [comment]
I think this is all working in `kanel` now. I'm looking at getting `kanel-kysely` working too then will make reviewable.

**Comment by domdomegg** [comment]
I think that should do it. I've tested with the horrific example in https://github.com/kristiandupont/kanel/issues/505 and it passes perfectly with both `kanel` and `kanel-kysely`. All the tests pass (although will flag that I don't think kanel-kysely or kanel-zod currently have a test setup).

**Review by kristiandupont — APPROVED** [review]

**Comment by kristiandupont** [comment]
Wow, you put a lot of work into this and managed to stay true to my weird conventions and patterns, that's impressive! Thank you!

**Comment by kristiandupont** [comment]
Both packages are published

**Comment by domdomegg** [comment]
Thank you for reviewing, approving, merging and releasing so fast! This is a huge help :)

Have a brilliant weekend.

**Pull request merged**
