### PR TITLE
Fix composite type declaration with a "type" composite fragment 

### PR DESCRIPTION
**Pull request by kfirba**
Hey.

I have a pivot table with a composite key, where a fragment of the primary key is an enum:

```sql
create type "TopupType" as enum('A', 'B', 'C', 'D', 'E', 'F');

create table "Topups" (
  "someOtherTableId" text not null references "SomeOtherTable" ("id") on delete cascade on update restrict,
  "type" "TopupType" not null,
  -- ...
  primary key ("someOtherTableId", "type")
);
```

Without this PR, there's a faulty generated type for this table:

```ts
export const topupsType: z.Schema<TopupsType> = undefined as any;
```

It happens since the `getIdentifierDeclaration` function has no awareness of other non-composite types.
This PR falls back to inspect the `nonCompositeTypeImports` object in case the composite type is not part of the built-in type mappings.

The result now is:

```ts
export const topupsType: z.Schema<TopupsType> = topupType as any;
```

### CODE REVIEW

**Comment by kristiandupont** [comment]
Hi @kfirba, thank you for the contribution! There are some linter errors, if you fix those I will merge it :-)

**Comment by kfirba** [comment]
@kristiandupont The linting issues are not from the change I made, they are there in `main`, I suppose.
I can take a look

**Comment by kristiandupont** [comment]
Ah, then perhaps it's because I updated some dependencies recently. CI should have caught that but I tend to merge many at a time so sometimes things slip through..

**Comment by kristiandupont** [comment]
Indeed the problem is on `main`. I'm fixing it.

**Comment by kfirba** [comment]
@kristiandupont Great :) 
Let me know when it's in so I can rebase and update the PR

**Comment by kristiandupont** [comment]
Try now!

**Comment by kfirba** [comment]
@kristiandupont Should be good now :)

**Comment by kristiandupont** [comment]
Merged and published. Thank you for contributing, nice find!

**Comment by kfirba** [comment]
Thanks for the package!

**Pull request merged**
