### PR TITLE
Better support for arrays of enums

### PR DESCRIPTION
**Pull request by jcristovao**
As mentioned [here](https://github.com/kristiandupont/extract-pg-schema/issues/2#issuecomment-829252948), array support can be improved by having a specific field indicating an array, and storing a subType with the 'array of' information.

The goal is that [kanel](https://github.com/kristiandupont/kanel) then has sufficient information to handle arrays of enums, and can then include the associated enums imports ([Associated PR on extract-pg-schema here](https://github.com/kristiandupont/extract-pg-schema/pull/105))

The fix here just looks into the new `isArray` field to see what should be considered as the base type, the previous `type` or the new `subType`

Let me know what you think, thank you!

EDIT: this one will only work once the one from extract-pg-schema is merged

### CODE REVIEW

**Comment by kristiandupont** [comment]
Hey, extract-pg-schema is bumped, would you mind rebasing this?

**Comment by pbernasconi** [comment]
This would be super helpful for our project – can I submit a PR To get this merged and fixed?

**Comment by kristiandupont** [comment]
Released in 2.2.0. Let me know if it works for you -- I don't have any arrays of enums in my schema at the moment.

**Comment by pbernasconi** [comment]
Works great! thanks for the release :)

**Pull request closed without merging**
