### PR TITLE
Add example for kanel-kysely, fix some generation issues

### PR DESCRIPTION
**Pull request by thelinuxlich**
Now we can use the dvd-rental db to generate kysely definitions in a example folder too and few changes to the definition generation

### CODE REVIEW

**Comment by kristiandupont** [comment]
So I added the New* and *Update according to the example from https://kysely.dev/docs/getting-started -- are those not classes that you typically use, or are they not relevant in this situation for some reason?

**Comment by thelinuxlich** [comment]
I talked with one of the Kysely maintainers about it and I'm reverting back the generation of Selectable, Insertable and Updateable because the end user sometimes wanna import these to cast the shape of objects. But PublicSchema will import the Table type

**Comment by kristiandupont** [comment]
Got it. Could you run Prettier on it and push, I'll merge and publish a new version then!

**Comment by thelinuxlich** [comment]
> Got it. Could you run Prettier on it and push, I'll merge and publish a new version then!

You mean the lint task? Because when I run prettier it shows a lot of files unformatted

**Comment by thelinuxlich** [comment]
Another thing I've changed is that when you have a Date field, for insert and update should accept "Date | string"

**Comment by thelinuxlich** [comment]
Oh and one thing I noticed, `enumStyle: 'union'` doesn't change how MpaaRating enum is generated

**Comment by kristiandupont** [comment]
>Another thing I've changed is that when you have a Date field, for insert and update should accept "Date | string"

I saw that. It seems to me that this probably is not isolated to `Date` but almost any non-number type? But this is a good start, let's see what type of issues people run into.

Thank you for contributing!

**Comment by kristiandupont** [comment]
[kanel-kysely](https://www.npmjs.com/package/kanel-kysely) is published. Thank you @thelinuxlich!

**Comment by thelinuxlich** [comment]
Once published I'll make an announcement on Kysely channel, we will probably receive a new influx of users here :)

**Comment by kristiandupont** [comment]
It's published now!

**Pull request merged**
